=== datagov-cz/otevrene-formalni-normy/faktury/draft/schémata/faktury.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://data.gov.cz/otevřené-formální-normy/faktury/draft/schémata/faktury.json",
    "type": "array",
    "title": "Faktury",
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "Faktura",
        "properties": {
            "id": {
                "$id": "#/items/properties/id",
                "type": "string",
                "title": "Identifikátor",
                "examples": [
                    "bc81c7e2-6971-4553-a4f8-47754eec9365"
                ]
            },
            "typ_dokladu": {
                "$id": "#/items/properties/typ_dokladu",
                "type": "string",
                "title": "Typ dokladu",
                "examples": [
                    "Přijatá faktura"
                ]
            },
            "částka_bez_dph": {"$ref":"https://data.gov.cz/otevřené-formální-normy/základní-datové-typy/draft/schémata/částka.json"},
            "částka_s_dph": {
                          "$ref":"https://data.gov.cz/otevřené-formální-normy/základní-datové-typy/draft/schémata/částka.json" },
            "částka_uhrazená": {
                          "$ref":"https://data.gov.cz/otevřené-formální-normy/základní-datové-typy/draft/schémata/částka.json" },
            "částka_celkem_devizy": {
                          "$ref":"https://data.gov.cz/otevřené-formální-normy/základní-datové-typy/draft/schémata/částka.json" },
            "datum_úhrady": {
                "$id": "#/items/properties/datum_úhrady",
                "type": "string",
				"format": "date",
                "title": "Datum úhrady",
                "examples": [
                    "2019-01-01"
                ]
            },
            "datum_vystavení": {
                "$id": "#/items/properties/datum_vystavení",
                "type": "string",
				"format": "date",
                "title": "Datum vystavení",
                "examples": [
                    "2019-01-01"
                ]
            },
            "datum_splatnosti": {
                "$id": "#/items/properties/datum_splatnosti",
                "type": "string",
				"format": "date",
                "title": "Datum splatnosti",
                "examples": [
                    "2019-01-01"
                ]
            },
            "datum_přijetí": {
                "$id": "#/items/properties/datum_přijetí",
                "type": "string",
				"format": "date",
                "title": "Datum přijetí",
                "examples": [
                    "2019-01-01"
                ]
            },
            "datum_plnění": {
                "$id": "#/items/properties/datum_plnění",
                "type": "string",
				"format": "date",
                "title": "Datum plnění",
                "examples": [
                    "2019-01-01"
                ]
            },
            "identifikátor_dodavatele": {
                "$id": "#/items/properties/identifikátor_dodavatele",
                "type": "string",
                "title": "Identifikátor dodavatele",
                "examples": [
                    "ABCD123"
                ]
            },
            "identifikátor_odběratele": {
                "$id": "#/items/properties/identifikátor_odběratele",
                "type": "string",
                "title": "Identifikátor odběratele",
                "examples": [
                    "DCBA123"
                ]
            },
            "účel_platby": {
                "$id": "#/items/properties/účel_platby",
                "type": "string",
                "title": "účel_platby",
                "examples": [
                    "Rekonstrukce chodníku"
                ]
            },
            "url": {
                "$id": "#/items/properties/url",
                "type": "string",
                "title": "URL faktury ke stažení",
                "examples": [
                    "https://doklady.cz/faktury/1234"
                ]
            },
            "identifikátor_smlouvy": {
                "$id": "#/items/properties/identifikátor_smlouvy",
                "type": "string",
                "title": "Identifikátor smlouvy",
                "examples": [
                    "AA-1564896489"
                ]
            },
            "kapitola_rozpočtu": {
                "$id": "#/items/properties/kapitola_rozpočtu",
                "type": "array",
                "title": "Kapitoly rozpočtu",
                "items": {
                    "$id": "#/items/properties/kapitola_rozpočtu/items",
                    "type": "object",
                    "title": "Kapitola rozpočtu",
                    "properties": {
                        "číslo": {
                            "$id": "#/items/properties/kapitola_rozpočtu/items/properties/číslo",
                            "type": "string",
                            "title": "Číslo kapitoly rozpočtu",
                            "examples": [
                                "303"
                            ]
                        },
                        "název": {
                            "$id": "#/items/properties/kapitola_rozpočtu/items/properties/název",
                            "type": "string",
                            "title": "Název kapitoly rozpočtu",
                            "examples": [
                                "Senát Parlamentu"
                            ]
                        }
                    }
                }
            },
            "dodavatel": { "$ref": "https://data.gov.cz/otevřené-formální-normy/lidé-a-osoby/draft/schémata/člověk-či-osoba.json" },
            "odběratel": { "$ref": "https://data.gov.cz/otevřené-formální-normy/lidé-a-osoby/draft/schémata/člověk-či-osoba.json" },
            "položka_faktury": {
                "$id": "#/items/properties/položka_faktury",
                "type": "array",
                "title": "Položky faktury",
                "items": {
                    "$id": "#/items/properties/položka_faktury/items",
                    "type": "object",
                    "title": "Položka faktury",
                    "properties": {
                        "název": {
                            "$id": "#/items/properties/položka_faktury/items/properties/název",
                            "type": "string",
                            "title": "Název položky",
                            "examples": [
                                "Písek"
                            ]
                        },
                        "množství": {
                          "$ref":"https://data.gov.cz/otevřené-formální-normy/základní-datové-typy/draft/schémata/množství.json" },
                        "částka_bez_dph_jednotka": {
                          "$ref":"https://data.gov.cz/otevřené-formální-normy/základní-datové-typy/draft/schémata/částka.json" },
                        "částka_bez_dph_celkem": {
                          "$ref":"https://data.gov.cz/otevřené-formální-normy/základní-datové-typy/draft/schémata/částka.json" },
                        "sazba_dph": {
                            "$id": "#/items/properties/položka_faktury/items/properties/sazba_dph",
                            "type": "number",
                            "title": "Sazba DPH",
                            "examples": [
                                1.21
                            ]
                        },
                        "položka_rozpočtu": {
                            "$id": "#/items/properties/položka_faktury/items/properties/položka_rozpočtu",
                            "type": "array",
                            "title": "Položky rozpočtu",
                            "items": {
                                "$id": "#/items/properties/položka_faktury/items/properties/položka_rozpočtu/items",
                                "type": "object",
                                "title": "Položka rozpočtu",
                                "properties": {
                                    "číslo": {
                                        "$id": "#/items/properties/položka_faktury/items/properties/položka_rozpočtu/items/properties/číslo",
                                        "type": "string",
                                        "title": "The Číslo Schema",
                                        "examples": [
                                            "1111"
                                        ]
                                    },
                                    "název": {
                                        "$id": "#/items/properties/položka_faktury/items/properties/položka_rozpočtu/items/properties/název",
                                        "type": "string",
                                        "title": "The Název Schema",
                                        "examples": [
                                            "Daň z příjmů fyzických osob placená plátci"
                                        ]
                                    }
                                }
                            }
                        },
                        "analytický_účet": {
                            "$id": "#/items/properties/položka_faktury/items/properties/analytický_účet",
                            "type": "array",
                            "title": "Analytické účty",
                            "items": {
                                "$id": "#/items/properties/položka_faktury/items/properties/analytický_účet/items",
                                "type": "object",
                                "title": "Analytický účet",
                                "properties": {
                                    "číslo": {
                                        "$id": "#/items/properties/položka_faktury/items/properties/analytický_účet/items/properties/číslo",
                                        "type": "string",
                                        "title": "Číslo analytického účtu",
                                        "examples": [
                                            "511/100"
                                        ]
                                    },
                                    "název": {
                                        "$id": "#/items/properties/položka_faktury/items/properties/analytický_účet/items/properties/název",
                                        "type": "string",
                                        "title": "Název analytického účtu",
                                        "examples": [
                                            "Náklady na reprezentaci"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== datagov-cz/otevrene-formalni-normy/faktury/draft/příklady/1.json
[
  {
    "id": "bc81c7e2-6971-4553-a4f8-47754eec9365",
    "typ_dokladu": "Přijatá faktura",
    "částka_bez_dph": {
      "výše": 1000.1,
      "měna": "CZK"
    },
    "částka_s_dph": {
      "výše": 1000.1,
      "měna": "CZK"
    },
    "částka_uhrazená": {
      "výše": 1000.1,
      "měna": "CZK"
    },
    "částka_celkem_devizy": {
      "výše": 1000.1,
      "měna": "EUR"
    },
    "datum_úhrady": "2019-01-01",
    "datum_vystavení": "2019-01-01",
    "datum_splatnosti": "2019-01-01",
    "datum_přijetí": "2019-01-01",
    "datum_plnění": "2019-01-01",
    "identifikátor_dodavatele": "ABCD123",
    "identifikátor_odběratele": "DCBA123",
    "účel_platby": "Rekonstrukce chodníku",
    "url": "https://doklady.cz/faktury/1234",
    "identifikátor_smlouvy": "AA-1564896489",
    "kapitola_rozpočtu": [
      {
        "číslo": "303",
        "název": "Senát Parlamentu"
      },
      {
        "číslo": "301",
        "název": "Kancelář prezidenta republiky"
      }
    ],
    "dodavatel": {
      "osoba": {
        "název": "Kosovská banka",
        "stát_registrace": {
          "kód": "1A0",
          "název": "Kosovo"
        }
      }
    },
    "odběratel": {
      "osoba": {
        "ičo": "00024341",
        "název": "Ministerstvo zdravotnictví"
      }
    },
    "položka_faktury": [
      {
        "název": "Písek",
        "množství": {
          "hodnota": 23.0,
          "jednotka": "KGM"
        },
        "částka_bez_dph_jednotka": {
          "výše": 1024.12,
          "měna": "CZK"
        },
        "částka_bez_dph_celkem": {
          "výše": 23554.76,
          "měna": "CZK"
        },
        "sazba_dph": 1.21,
        "položka_rozpočtu": [
          {
            "číslo": "1111",
            "název": "Daň z příjmů fyzických osob placená plátci"
          }
        ],
        "analytický_účet": [
          {
            "číslo": "511/100",
            "název": "Náklady na reprezentaci"
          }
        ]
      },
      {
        "název": "Jiný písek",
        "množství": {
          "hodnota": 23.0,
          "jednotka": "KGM"
        },
        "částka_bez_dph_jednotka": {
          "výše": 1024.12,
          "měna": "CZK"
        },
        "částka_bez_dph_celkem": {
          "výše": 23554.76,
          "měna": "CZK"
        },
        "sazba_dph": 1.21,
        "položka_rozpočtu": [
          {
            "číslo": "1111",
            "název": "Daň z příjmů fyzických osob placená plátci"
          }
        ],
        "analytický_účet": [
          {
            "číslo": "511/100",
            "název": "Náklady na reprezentaci"
          }
        ]
      }
    ]
  }
]
