=== datagov-cz/otevrene-formalni-normy/společné-části-elektronických-dokumentů/2024-10-04/schémata/osoby/eIDASNaturalPerson.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://eidas.europa.eu/attributes/naturalperson"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://eidas.europa.eu/attributes/naturalperson" 
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified" 
    version="1">
    <xsd:attribute name="LatinScript" type="xsd:boolean" default="true"/>

    <xsd:complexType name="NaturalPersonType">
        <xsd:sequence>
            <!-- Mandatory attribute types for a natural person. -->
            <xsd:element name="FamilyName" type="CurrentFamilyNameType"/>
            <xsd:element name="FirstName" type="CurrentGivenNameType"/>
            <xsd:element name="DateOfBirth" type="DateOfBirthType"/>
            <xsd:element name="PersonIdentifier" type="PersonIdentifierType"/>

            <!-- Optional attribute types for a natural person. -->
            <xsd:element name="BirthName" type="BirthNameType" minOccurs="0"/>
            <xsd:element name="PlaceOfBirth" type="PlaceOfBirthType" minOccurs="0"/>
            <xsd:element name="CurrentAddress" type="CurrentAddressType" minOccurs="0"/>
            <xsd:element name="Gender" type="GenderType" minOccurs="0"/>
            <xsd:element name="Nationality" type="NationalityType" minOccurs="0"/>
            <xsd:element name="CountryOfBirth" type="CountryOfBirthType" minOccurs="0"/>
            <xsd:element name="TownOfBirth" type="xsd:string" minOccurs="0"/>
            <xsd:element name="CountryOfResidence" type="CountryOfResidenceType" minOccurs="0"/>
            <xsd:element name="PhoneNumber" type="xsd:string" minOccurs="0"/>
            <xsd:element name="EmailAddress" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="PersonIdentifierType">
        <xsd:annotation>
            <xsd:documentation> Unique identifier for the natural person as defined by the eIDAS Regulation. </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:complexType name="CurrentFamilyNameType">
        <xsd:annotation>
            <xsd:documentation> Current family name of the natural person. </xsd:documentation>
        </xsd:annotation>
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute ref="LatinScript"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="CurrentGivenNameType">
        <xsd:annotation>
            <xsd:documentation> Current given names of the natural person. </xsd:documentation>
        </xsd:annotation>
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute ref="LatinScript"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:simpleType name="DateOfBirthType">
        <xsd:annotation>
            <xsd:documentation> Date of Birth for the Natural Person (Based on xsd:date i.e. YYYY-MM-DD format). </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:date"/>
    </xsd:simpleType>

    <xsd:complexType name="CurrentAddressStructuredType">
        <xsd:annotation>
            <xsd:documentation> Current address of the natural person. </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="PoBox" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="LocatorDesignator" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="LocatorName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="CvaddressArea" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="Thoroughfare" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="PostName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="AdminunitFirstline" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="AdminunitSecondline" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="PostCode" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="CurrentAddressType">
        <xsd:annotation>
            <xsd:documentation> Current address of the natural person as a base64 encoded string. </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:simpleType name="GenderType">
        <xsd:annotation>
            <xsd:documentation> Gender of the natural person. </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Male"/>
            <xsd:enumeration value="Female"/>
            <xsd:enumeration value="Unspecified"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="BirthNameType">
        <xsd:annotation>
            <xsd:documentation> First name(s) and family name(s) of the natural person at birth. </xsd:documentation>
        </xsd:annotation>
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute ref="LatinScript"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="PlaceOfBirthType">
        <xsd:annotation>
            <xsd:documentation> Place of birth for a natural person. </xsd:documentation>
        </xsd:annotation>
        <xsd:simpleContent>
            <xsd:extension base="xsd:string"></xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:simpleType name="NationalityType">
        <xsd:annotation>
            <xsd:documentation> Nationality of the natural person (Two-letter country codes according to ISO 3166-1 standard).
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z][A-Z]"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="CountryOfBirthType">
        <xsd:annotation>
            <xsd:documentation> Country of birth of the natural person (Two-letter country code according to ISO 3166-1 standard). </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z][A-Z]"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="CountryOfResidenceType">
        <xsd:annotation>
            <xsd:documentation> Country of residence of the natural person (Two-letter country code according to ISO 3166-1 standard). </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z][A-Z]"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="NaturalPerson" type="NaturalPersonType"/>
</xsd:schema>

=== datagov-cz/otevrene-formalni-normy/společné-části-elektronických-dokumentů/2024-10-04/příklady/eIDASNaturalPerson.xml
<?xml version="1.0" encoding="UTF-8"?>
<NaturalPerson 
xmlns="http://eidas.europa.eu/attributes/naturalperson" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:eidas-np="http://eidas.europa.eu/attributes/naturalperson" 
xsi:schemaLocation="http://eidas.europa.eu/attributes/naturalperson https://ofn.gov.cz/společné-části-elektronických-dokumentů/2024-10-04/schémata/osoby/eIDASNaturalPerson.xsd">
	<FamilyName eidas-np:LatinScript="true">Smith</FamilyName>
	<FirstName eidas-np:LatinScript="true">John</FirstName>
	<DateOfBirth>1957-08-14</DateOfBirth>
	<PersonIdentifier>eidas999777888</PersonIdentifier>
	<BirthName eidas-np:LatinScript="true">Smith</BirthName>
	<PlaceOfBirth>London</PlaceOfBirth>
	<CurrentAddress>Berlin</CurrentAddress>
	<Gender>Unspecified</Gender>
	<Nationality>GB</Nationality>
	<CountryOfBirth>AT</CountryOfBirth>
	<TownOfBirth>Vienna</TownOfBirth>
	<CountryOfResidence>GB</CountryOfResidence>
	<PhoneNumber>+122233344-7</PhoneNumber>
	<EmailAddress>joh@smith.com</EmailAddress>
</NaturalPerson>
