=== datagov-cz/otevrene-formalni-normy/společné-části-elektronických-dokumentů/2024-10-04/schémata/osoby/fyzická-osoba.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1" elementFormDefault="qualified" targetNamespace="http://dia.gov.cz/ns/spolecne-casti-elektronickych-dokumentu/osoby" xmlns:osoby="http://dia.gov.cz/ns/spolecne-casti-elektronickych-dokumentu/osoby" xmlns:místa="http://dia.gov.cz/ns/spolecne-casti-elektronickych-dokumentu/mista" xmlns:sawsdl="http://www.w3.org/ns/sawsdl">
  <xs:import namespace="http://dia.gov.cz/ns/spolecne-casti-elektronickych-dokumentu/mista" schemaLocation="https://ofn.gov.cz/společné-části-elektronických-dokumentů/2024-10-04/schémata/místa/místo.xsd"/>
  <xs:complexType name="fyzická_osoba" sawsdl:modelReference="https://slovník.gov.cz/generický/standard-pro-elektronické-dokumenty/pojem/fyzická-osoba-jako-osoba-ve-vztahu-k-dokumentu">
    <xs:annotation>
      <xs:documentation xml:lang="cs">
        Fyzická osoba jako osoba ve vztahu k dokumentu
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="jméno" type="xs:string" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/jméno-fyzické-osoby">
        <xs:annotation>
          <xs:documentation xml:lang="cs">
            jméno fyzické osoby - Jméno člověka je jeho osobní jméno a příjmení, popřípadě jeho další jména a rodné příjmení, která mu podle zákona náležejí. Každý člověk má právo užívat své jméno v právním styku, stejně jako právo na ochranu svého jména a na úctu k němu.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="další_jména" type="xs:string" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/další-jméno-fyzické-osoby">
        <xs:annotation>
          <xs:documentation xml:lang="cs">
            další jméno fyzické osoby
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="příjmení" type="xs:string" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/příjmení-fyzické-osoby">
        <xs:annotation>
          <xs:documentation xml:lang="cs">
            příjmení fyzické osoby
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="rodné_příjmení" type="xs:string" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/rodné-příjmení-fyzické-osoby">
        <xs:annotation>
          <xs:documentation xml:lang="cs">
            rodné příjmení fyzické osoby
          </xs:documentation>
        </xs:annotation>
      </xs:element>
       <xs:element name="datum_narození" type="xs:date" sawsdl:modelReference="https://slovník.gov.cz/generický/eu-1501-2015-e-idas-prováděcí/pojem/datum-narození">
        <xs:annotation>
          <xs:documentation xml:lang="cs">
            datum narození
          </xs:documentation>
        </xs:annotation>
      </xs:element>
     <xs:sequence>
        <xs:element name="trvalé_bydliště" type="místa:místo" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/má-místo-bydliště">
          <xs:annotation>
            <xs:documentation xml:lang="cs">
              má místo bydliště
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
      <xs:sequence minOccurs="0">
        <xs:element name="datová_schránka" type="xs:string" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/111/2009/pojem/má-identifikátor-datové-schránky">
          <xs:annotation>
            <xs:documentation xml:lang="cs">
              Má identifikátor datové schránky - Jednoznačný identifikátor datové schránky.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="fyzická_osoba" type="osoby:fyzická_osoba"/>
</xs:schema>

=== datagov-cz/otevrene-formalni-normy/společné-části-elektronických-dokumentů/2024-10-04/příklady/fyzická-osoba.xml
<?xml version="1.0" encoding="UTF-8"?>
<fyzická_osoba 
xmlns="http://dia.gov.cz/ns/spolecne-casti-elektronickych-dokumentu/osoby" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:místa="http://dia.gov.cz/ns/spolecne-casti-elektronickych-dokumentu/mista" 
xsi:schemaLocation="http://dia.gov.cz/ns/spolecne-casti-elektronickych-dokumentu/osoby https://ofn.gov.cz/společné-části-elektronických-dokumentů/2024-10-04/schémata/osoby/fyzická-osoba.xsd">
	<jméno>Jana</jméno>
	<další_jména>Filoména</další_jména>
	<příjmení>Novotný</příjmení>
	<rodné_příjmení>Svobodová</rodné_příjmení>
	<datum_narození>2023-08-13</datum_narození>
	<trvalé_bydliště>
		<místa:adresní_místo>
			<místa:kód_adresního_místa>123456789</místa:kód_adresního_místa>
		</místa:adresní_místo>
	</trvalé_bydliště>
	<datová_schránka>abcdef</datová_schránka>
</fyzická_osoba>
