=== datagov-cz/otevrene-formalni-normy/společné-části-elektronických-dokumentů/2024-10-04/schémata/osoby/podnikající-fyzická-osoba-nezapsaná-v-or.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1" elementFormDefault="qualified" targetNamespace="https://ofn.gov.cz/společné-části-elektronických-dokumentů/2024-10-04/osoby" xmlns:osoby="https://ofn.gov.cz/společné-části-elektronických-dokumentů/2024-10-04/osoby" xmlns:místa="https://ofn.gov.cz/společné-části-elektronických-dokumentů/2024-10-04/místa" xmlns:sawsdl="http://www.w3.org/ns/sawsdl">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
  <xs:import namespace="https://ofn.gov.cz/společné-části-elektronických-dokumentů/2024-10-04/místa" schemaLocation="../místa/místo.xsd"/>
  <xs:complexType name="langString">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="xml:lang" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="podnikající_fyzická_osoba_nezapsaná_v_or" sawsdl:modelReference="https://slovník.gov.cz/generický/standard-pro-elektronické-dokumenty/pojem/podnikající-fyzická-osoba-nezapsaná-v-obchodním-rejstříku-jako-osoba-ve-vztahu-k-dokumentu">
    <xs:annotation>
      <xs:documentation>Význam: https://slovník.gov.cz/generický/standard-pro-elektronické-dokumenty/pojem/podnikající-fyzická-osoba-nezapsaná-v-obchodním-rejstříku-jako-osoba-ve-vztahu-k-dokumentu
Název (cs): Podnikající fyzická osoba nezapsaná v obchodním rejstříku jako osoba ve vztahu k dokumentu</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="jméno" type="xs:string" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/jméno-fyzické-osoby">
        <xs:annotation>
          <xs:documentation>Význam: https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/jméno-fyzické-osoby
Název (cs): jméno fyzické osoby
Popis (cs): Jméno člověka je jeho osobní jméno a příjmení, popřípadě jeho další jména a rodné příjmení, která mu podle zákona náležejí. Každý člověk má právo užívat své jméno v právním styku, stejně jako právo na ochranu svého jména a na úctu k němu.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="další_jména" type="xs:string" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/další-jméno-fyzické-osoby">
        <xs:annotation>
          <xs:documentation>Význam: https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/další-jméno-fyzické-osoby
Název (cs): další jméno fyzické osoby</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="příjmení" type="xs:string" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/příjmení-fyzické-osoby">
        <xs:annotation>
          <xs:documentation>Význam: https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/příjmení-fyzické-osoby
Název (cs): příjmení fyzické osoby</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="datum_narození" type="xs:date" sawsdl:modelReference="https://slovník.gov.cz/generický/eu-1501-2015-e-idas-prováděcí/pojem/datum-narození">
        <xs:annotation>
          <xs:documentation>Význam: https://slovník.gov.cz/generický/eu-1501-2015-e-idas-prováděcí/pojem/datum-narození
Název (cs): datum narození
Popis (cs): </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="dodatky" type="osoby:langString" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/dodatky-charakterizující-blíže-osobu-podnikatele-nebo-obchodní-závod">
        <xs:annotation>
          <xs:documentation>Význam: https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/dodatky-charakterizující-blíže-osobu-podnikatele-nebo-obchodní-závod
Název (cs): dodatky charakterizující blíže osobu podnikatele nebo obchodní závod</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:sequence minOccurs="0">
        <xs:element name="datová_schránka" type="xs:string" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/111/2009/pojem/má-identifikátor-datové-schránky">
          <xs:annotation>
            <xs:documentation>Význam: https://slovník.gov.cz/legislativní/sbírka/111/2009/pojem/má-identifikátor-datové-schránky
Název (cs): Má identifikátor datové schránky
Popis (cs): Jednoznačný identifikátor datové schránky.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
      <xs:sequence>
        <xs:element name="trvalé_bydliště" type="místa:místo" sawsdl:modelReference="https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/má-místo-bydliště">
          <xs:annotation>
            <xs:documentation>Význam: https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/má-místo-bydliště
Název (cs): má místo bydliště</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
      <xs:element minOccurs="0" name="doručovací_místo" type="místa:místo" sawsdl:modelReference="https://slovník.gov.cz/generický/standard-pro-elektronické-dokumenty/pojem/doručovací-místo">
        <xs:annotation>
          <xs:documentation>Význam: https://slovník.gov.cz/generický/standard-pro-elektronické-dokumenty/pojem/doručovací-místo
Název (cs): doručovací místo</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="pfo_nz_or">
    <xs:choice>
      <xs:element name="podnikající_fyzická_osoba_nezapsaná_v_or" type="osoby:podnikající_fyzická_osoba_nezapsaná_v_or"/>
    </xs:choice>
  </xs:complexType>
</xs:schema>

=== datagov-cz/otevrene-formalni-normy/společné-části-elektronických-dokumentů/2024-10-04/příklady/podnikající-fyzická-osoba-nezapsaná-v-or.xml
<?xml version="1.0" encoding="UTF-8"?>
<podnikající_fyzická_osoba_nezapsaná_v_or 
xmlns="http://dia.gov.cz/ns/spolecne-casti-elektronickych-dokumentu/osoby" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:místa="http://dia.gov.cz/ns/spolecne-casti-elektronickych-dokumentu/mista"
xsi:schemaLocation="http://dia.gov.cz/ns/spolecne-casti-elektronickych-dokumentu/osoby https://ofn.gov.cz/společné-části-elektronických-dokumentů/2024-10-04/schémata/osoby/podnikající-fyzická-osoba-nezapsaná-v-or.xsd">
	<jméno>Jan</jméno>
	<další_jména>Jaromír Hynek</další_jména>
	<příjmení>Novák</příjmení>
	<datum_narození>1957-08-13</datum_narození>
	<dodatky xml:lang="cs">Klempíř</dodatky>
	<datová_schránka>abcdef</datová_schránka>
	<trvalé_bydliště>
		<místa:zahraniční_adresa>
			<místa:text_adresy>Philharmoniker Str. 4, 1010 Wien, Austria</místa:text_adresy>
		</místa:zahraniční_adresa>
	</trvalé_bydliště>
</podnikající_fyzická_osoba_nezapsaná_v_or>
