=== datagov-cz/otevrene-formalni-normy/bezbariérovost/2020-07-01/schémata/bezbariérovost.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "https://ofn.gov.cz/bezbariérovost/2020-07-01/schémata/bezbariérovost.json",
	"type": "object",
	"title": "Bezbariérovost",
	"required": ["typ"],
	"properties": {
        "typ": {
            "oneOf": [{
				"const": "Bezbariérovost"
                },{
                "type": "array",
                "contains": {
					"const": "Bezbariérovost"
                },
                "items": {
                    "type": "string"
                }
            }]
        },
		"iri": {
			"type": "string",
			"format": "iri",
			"title": "Identifikátor",
			"examples": [
				"https://www.trebic.cz/zdroj/aktualita/2020/dopadení-lupiče-na-francouzské-ulici"
			]
		},
		"název": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/text.json"
		},
		"popis": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/text.json"
		},
		"vytvořeno": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/časový-okamžik.json"
		},
		"aktualizováno": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/časový-okamžik.json"
		},
		"relevantní_do": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/časový-okamžik.json"
		},
		"zneplatněno": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/časový-okamžik.json"
		},
		"příloha": {
			"$ref": "https://ofn.gov.cz/digitální-objekty/2020-07-01/schémata/digitální-objekty.json"
		},
		"okamžik_mapování": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/časový-okamžik.json"
		},
		"mapující_subjekt": {
			"type": "array",
			"items": {
				"$ref": "https://ofn.gov.cz/lidé-a-osoby/2020-07-01/schémata/člověk-či-osoba.json"
			}
		},
		"mapování_dle_metodiky": {
			"type": "boolean",
			"tittle": "Mapování dle metodiky kategorizace objektů",
			"examples": [true]
		},
		"přístupnost_děti_s_doprovodem": {
			"type": "string",
			"format": "iri",
			"pattern": "^https\\:\/\/data\\.mvcr\\.gov\\.cz\/zdroj\/číselníky\/stupně-přístupnosti\/položky\/.*$",
			"title": "Přístupnost pro děti s doprovodem",
			"examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
		},
		"přístupnost_senioři": {
			"type": "string",
			"format": "iri",
			"pattern": "^https\\:\/\/data\\.mvcr\\.gov\\.cz\/zdroj\/číselníky\/stupně-přístupnosti\/položky\/.*$",
			"title": "Přístupnost pro seniory",
			"examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
		},
		"tělesně_postižení_toaleta_přístupnost": {
			"type": "string",
			"format": "iri",
			"pattern": "^https\\:\/\/data\\.mvcr\\.gov\\.cz\/zdroj\/číselníky\/stupně-přístupnosti\/položky\/.*$",
			"title": "Přístupnost toalety pro tělesně postižené",
			"examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
		},
		"tělesně_postižení_objekt_přístupnost": {
			"type": "string",
			"format": "iri",
			"pattern": "^https\\:\/\/data\\.mvcr\\.gov\\.cz\/zdroj\/číselníky\/stupně-přístupnosti\/položky\/.*$",
			"title": "Přístupnost objektu pro tělesně postižené",
			"examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
		},
		"objekt_vyhrazené_parkování": {
			"type": "boolean",
			"title": "Vyhrazené parkovací stání",
			"description": "Říká, zda je u objektu alespoň jedno vyhrazené parkovací stání.",
			"default": false,
			"examples": [
				true
			]
		},
		"objekt_obtížný_povrch": {
			"type": "boolean",
			"title": "Obtížný povrch před objektem",
			"description": "Říká, zda je přístup k objektu obtížný, jedná se zejména o hrubou historickou dlažbu, popraskaný asfalt.",
			"default": false,
			"examples": [
				true
			]
		},
		"objekt_obtížný_sklon": {
			"type": "boolean",
			"title": "Obtížný povrch před objektem",
			"description": "Říká, zda je přístup k objektu obtížný z důvodu výrazného podélného nebo příčného sklonu.",
			"default": false,
			"examples": [
				true
			]
		},
		"vstup_hlavní_vchod": {
			"type": "boolean",
			"title": "Objekt přístupný hlavním vchodem",
			"description": "Říká, zda je do objektu bezbariérový přístup hlavním vchodem.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_schody": {
			"type": "integer",
			"title": "Počet schodů u hlavního vstupu",
			"description": "Říká, kolik je schodů před hlavním vstupem do objektu bez řešení jejich bezbariérového překonání.",
			"default": 0,
			"examples": [
				18
			]
		},
		"vstup_hlavní_nájezd": {
			"type": "boolean",
			"title": "Nájezd u hlavního vstupu",
			"description": "Říká, zda je u hlavního vstupu nájezd (rampa nebo ližiny) pro bezbariérový přístup do objektu. Šířka pevných ramp je minimálně 110 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_plošina": {
			"type": "boolean",
			"title": "Plošina u hlavního vstupu",
			"description": "Říká, zda je u hlavního vstupu schodišťová plošina pro bezbariérový přístup do objektu. Rozměry plošiny jsou minimálně: šířka vstupu 70 cm, přepravní plocha – šířka 70 cm x hloubka 90 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_výtah": {
			"type": "boolean",
			"title": "Výtah u hlavního vstupu",
			"description": "Říká, zda je u hlavního vstupu výtah (zdviž) pro bezbariérový přístup do objektu. Výtah má minimální rozměry: šířka dveří 70cm, vnitřní rozměr kabiny – šířka 100 cm x hloubka 110 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_výtah_sedátko": {
			"type": "boolean",
			"title": "Sedátko ve výtahu u hlavního vstupu",
			"description": "Říká, zda je výtah (zdviž) u hlavního vstupu vybaven sklopným sedátkem.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_výtah_madlo": {
			"type": "boolean",
			"title": "Madlo ve výtahu u hlavního vstupu",
			"description": "Říká, zda je výtah (zdviž) u hlavního vstupu vybeven madlem.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_šířka_dveří": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/množství.json"
		},
		"vstup_vedlejší_vchod": {
			"type": "boolean",
			"title": "Objekt přístupný vedlejším vchodem",
			"description": "Říká, zda je do objektu bezbariérový přístup vedlejším vchodem.",
			"default": false,
			"examples": [
				true
			]
		},
		"vstup_vedlejší_schody": {
			"type": "integer",
			"title": "Počet schodů u vedlejšího vstupu",
			"description": "Říká, kolik je schodů před vedlejším vstupem do objektu bez řešení jejich bezbariérového překonání.",
			"default": 0,
			"examples": [
				0
			]
		},
		"vstup_vedlejší_nájezd": {
			"type": "boolean",
			"title": "Nájezd u vedlejšího vstupu",
			"description": "Říká, zda je u vedlejšího vstupu nájezd (rampa nebo ližiny) pro bezbariérový přístup do objektu. Šířka pevných ramp je minimálně 110 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_vedlejší_plošina": {
			"type": "boolean",
			"title": "Plošina u vedlejšího vstupu",
			"description": "Říká, zda je u vedlejšího vstupu schodišťová plošina pro bezbariérový přístup do objektu. Rozměry plošiny jsou minimálně: šířka vstupu 70 cm, přepravní plocha – šířka 70 cm x hloubka 90 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_vedlejší_výtah": {
			"type": "boolean",
			"title": "Výtah u vedlejšího vstupu",
			"description": "Říká, zda je u vedlejšího vstupu výtah (zdviž) pro bezbariérový přístup do objektu. Výtah má minimální rozměry: šířka dveří 70cm, vnitřní rozměr kabiny – šířka 100 cm x hloubka 110 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_vedlejší_výtah_sedátko": {
			"type": "boolean",
			"title": "Sedátko ve výtahu u vedlejšího vstupu",
			"description": "Říká, zda je výtah (zdviž) u vedlejšího vstupu vybaven sklopným sedátkem.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_vedlejší_výtah_madlo": {
			"type": "boolean",
			"title": "Madlo ve výtahu u vedlejšího vstupu",
			"description": "Říká, zda je výtah (zdviž) u vedlejšího vstupu vybaven madlem.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_vedlejší_šířka_dveří": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/množství.json"
		},
		"interiér_schody": {
			"type": "integer",
			"title": "Počet schodů v interiéru",
			"description": "Říká, kolik je v interiéru nejvíce schodů, které nespojují patra.",
			"default": 0,
			"examples": [
				5
			]
		},
		"interiér_minimální_průchod": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/množství.json"
		},
		"interiér_výška_prahu": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/množství.json"
		},
		"interiér_přístupnost": {
			"type": "boolean",
			"title": "Přístupný interiér",
			"description": "Říká, zda je přístupný celý interiér nebo jeho větší část alespoň jedním bezbariérovým vstupem. Návštěva je možná bez předchozí domluvy.",
			"default": false,
			"examples": [
				false
			]
		},
		"interiér_nájezd": {
			"type": "boolean",
			"title": "Nájezd v interiéru",
			"description": "Říká, zda je v interiéru nájezd (rampa nebo ližiny) pro překonání výškových rozdílů. Šířka pevných ramp je minimálně 110 cm.",
			"default": false,
			"examples": [
				true
			]
		},
		"interiér_plošina": {
			"type": "boolean",
			"title": "Plošina v interiéru",
			"description": "Říká, zda je v interiéru schodišťová plošina. Rozměry plošiny jsou minimálně: šířka vstupu 70 cm, přepravní plocha – šířka 70 cm x hloubka 90 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"interiér_výtah": {
			"type": "boolean",
			"title": "Výtah v interiéru",
			"description": "Říká, zda je v interiéru výtah (zdviž). Výtah má minimální rozměry: šířka dveří 70cm, vnitřní rozměr kabiny – šířka 100 cm x hloubka 110 cm.",
			"default": false,
			"examples": [
				true
			]
		},
		"interiér_výtah_sedátko": {
			"type": "boolean",
			"title": "Sedátko ve výtahu v interiéru",
			"description": "Říká, zda je výtah (zdviž) v interiéru vybaven sklopným sedátkem.",
			"default": false,
			"examples": [
				true
			]
		},
		"interiér_výtah_madlo": {
			"type": "boolean",
			"title": "Madlo ve výtahu v interiéru",
			"description": "Říká, zda je výtah (zdviž) v interiéru vybaven madlem.",
			"default": false,
			"examples": [
				true
			]
		},
		"interiér_točité_schodiště": {
			"type": "boolean",
			"title": "Točité schodiště v interiéru",
			"description": "Říká, zda je v interiéru točité schodiště.",
			"default": false,
			"examples": [
				false
			]
		},
		"toaleta_šířka_dveří": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/množství.json"
		},
		"toaleta_klíč": {
			"type": "boolean",
			"title": "Dveře na toaletu uzamčené",
			"description": "Říká, zda jsou vstupní dveře na toaletu uzamčeny.",
			"default": false,
			"examples": [
				false
			]
		},
		"toaleta_euroklíč": {
			"type": "boolean",
			"title": "Dveře na toaletu uzamčené Euroklíčem",
			"description": "Říká, zda jsou vstupní dveře na toaletu osazeny Eurozámkem. Více informací na stránkách projektu Euroklíč.",
			"default": false,
			"examples": [
				false
			]
		},
		"toaleta_dostatečný_rozměr": {
			"type": "boolean",
			"title": "Dostatečný rozměr kabiny toalety",
			"description": "Říká, zda je rozměr kabiny toalety minimální šířky 140 cm a hloubky 140 cm. Manipulační prostor je pak umístěný proti dveřím.",
			"default": false,
			"examples": [
				true
			]
		},
		"toaleta_signalizační_tlačítko": {
			"type": "boolean",
			"title": "Signalizační tlačítko na toaletě",
			"description": "Říká, zda je toaleta vybavena signalizačním tlačítkem pro přivolání pomoci.",
			"default": false,
			"examples": [
				false
			]
		},
		"toaleta_wc_boční_přístup": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/2020-07-01/schémata/množství.json"
		},
		"toaleta_wc_výška_sedátka": {
			"type": "boolean",
			"title": "Dostatečná výška sedátka WC",
			"description": "Říká, zda je výška sedátka WC mísy alespoň 45cm.",
			"default": false,
			"examples": [
				true
			]
		},
		"toaleta_wc_madlo": {
			"type": "boolean",
			"title": "Madlo u WC",
			"description": "Říká, zda je u WC alespoň jedno madlo.",
			"default": false,
			"examples": [
				true
			]
		},
		"toaleta_umyvadlo_dostatečný_prostor": {
			"type": "boolean",
			"title": "Dostatečný prostor pod umyvadlem",
			"description": "Říká, zda je podjezd umyvadla v hloubce 20 cm od jeho hrany dostatečný pro podjetí vozíku pro invalidy.",
			"default": false,
			"examples": [
				true
			]
		},
		"toaleta_přebalovací_pult": {
			"type": "boolean",
			"title": "Přebalovací pult na toaletě",
			"description": "Říká, zda je toaleta vybavena přebalovacím pultem.",
			"default": false,
			"examples": [
				false
			]
		},
		"Braillovo_písmo": {
			"type": "boolean",
			"title": "Braillovo písmo",
			"examples": [true]
		},
		"hlasový_asistent": {
			"type": "boolean",
			"tittle": "Hlasový asistent",
			"examples": [true]
		},
		"vodící_linie": {
			"type": "boolean",
			"tittle": "Vodící linie",
			"examples": [true]
		},
		"vodící_pes": {
			"type": "boolean",
			"tittle": "Vodící pes",
			"examples": [true]
		}
	}
}

=== datagov-cz/otevrene-formalni-normy/bezbariérovost/draft/příklady/2.json
{
	"typ": "Bezbariérovost",
	"popis": {
		"cs": "Hrad nabízí stálé i příležitostné muzejní expozice včetně kasemat. Z vyhlídkového ochozu se nabízí ojedinělý pohled na město Brno a jeho okolí. Po telefonické domluvě možnost parkování v areálu hradu. Bezbariérový vstup do hradu je bočními dveřmi středního křídla (vpravo), asistence zajistí mobilní nájezd. Bezbariérové WC ve všech patrech.",
		"en": "The castle offers permanent and occasional museum exhibits including casemates. There is a unique view around the Brno and its surroundings from the observation deck. Parking in the castle is possible after calling the reception. Barrier-free entrance to the castle is located in the middle wing of the castle (right). Assistance will ensure a mobile entrance. Barrier-free toilets are on all floors."
	},
	"okamžik_mapování": {
		"typ": "Časový okamžik",
		"datum_a_čas": "2019-09-27T09:30:00+02:00"
	},
	"příloha": [{
		"typ": "Digitální objekt",
		"url": "https://images-cdn.mapotic.com/bound/1600x900/n/_p_/media/image/geo/1304/83465/be654aec-b10d-40d4-87d4-34d0f98fd9a8.jpg",
		"autor_díla": [{
			"typ": "Člověk",
			"jméno": {
				"cs": "Jan"
			},
			"příjmení": {
				"cs": "Novák"
			}
		}],
		"typ_média": "http://www.iana.org/assignments/media-types/image/jpeg",
		"podmínky_užití": {
			"typ": "Podmínky užití",
			"obsahuje_autorské_dílo": true,
			"obsahuje_více_autorských_děl": false,
			"licence_autorského_díla": "https://creativecommons.org/licenses/by/4.0/",
			"originální_databáze": false,
			"ochrana_zvláštními_právy_pořizovatele_databáze": false,
			"obsahuje_osobní_údaje": false
		}
	}],
	"mapující_subjekt": [{
		"typ": "Osoba",
		"ičo": "44992785",
		"název": {
			"cs": "Město Brno"
		}
	}],
	"mapování_dle_metodiky": false,
	"tělesně_postižení_toaleta_přístupnost": "https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný",
	"tělesně_postižení_objekt_přístupnost": "https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný",
	"objekt_vyhrazené_parkování": true,
	"vstup_hlavní_nájezd": false,
	"vstup_hlavní_plošina": false,
	"vstup_hlavní_výtah": true
}
