=== datagov-cz/otevrene-formalni-normy/dřeviny/draft/schémata/dřeviny.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://ofn.gov.cz/dřeviny/draft/schémata/dřeviny.json",
  "type": "array",
  "title": "Dřeviny",
  "items": {
    "type": "object",
    "title": "Dřeviny",
    "properties": {
      "název": {
        "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
      },
      "poznámka": {
        "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
      },
      "druh_dřeviny": {
        "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
      },
      "obrázek": {
        "type": "array",
        "title": "URL obrázku dřeviny",
        "description": "URL obrázku dřeviny",
        "items": {
          "type": "string",
          "format": "iri",
          "title": "URL obrázku dřeviny",
          "description": "URL obrázku dřeviny",
          "examples": ["https://příklad.cz/obrázek.jpg"]
        }
      },
      "typ_dřeviny": {
        "type": "string",
        "format": "iri",
        "title": "URL typu dřeviny",
        "description": "URL typu dřeviny z číselníku",
        "examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/typy-dřevin/položky/listnatý-strom"],
        "pattern": "^https:\\/\\/data\\.mvcr\\.gov\\.cz\\/zdroj\\/číselníky\\/typy-dřevin\\/položky\\/.+$"
      },
      "kategorie_ochrany": {
        "type": "string",
        "format": "iri",
        "title": "URL typu ochrany",
        "description": "URL typu ochrany území z číselníku",
        "examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/kategorie-územní-ochrany/položky/přírodní-památka"],
        "pattern": "^^https:\\/\\/data\\.mvcr\\.gov\\.cz\\/zdroj\\/číselníky\\/kategorie-územní-ochrany\\/položky\\/.+$"
      },
      "umístění": {
        "$ref": "https://ofn.gov.cz/umístění/draft/schémata/umístění.json"
      },
      "členské_dřeviny": {
        "type": "array",
        "items": {
          "$ref": "https://ofn.gov.cz/dřeviny/draft/schémata/dřeviny.json"
        }
      }
    }
  }
}

=== datagov-cz/otevrene-formalni-normy/dřeviny/draft/příklady/1.json
[{
		"název": {
			"cs": "Smrk u obrázku na Miroslavi"
		},
		"poznámka": {
			"cs": "cca 1 km jižně od kostela v Lipové Lázních, u lesní cesty cca 200 m nad rekreačním areálem Miroslav"
		},
		"druh_dřeviny": {
			"cs": "Smrk ztepilý"
		},
		"obrázek": ["https://d34-a.sdn.szn.cz/d_34/c_img_G_K/qraBzdw.jpeg"],
		"typ_dřeviny": "https://data.mvcr.gov.cz/zdroj/číselníky/typy-dřevin/položky/jehličnatý-strom",
		"kategorie_ochrany": "https://data.mvcr.gov.cz/zdroj/číselníky/kategorie-územní-ochrany/položky/přírodní-památka",
		"umístění": {
			"geometrie": {
				"type": "Point",
				"coordinates": [50.22054209714138, 17.128712012726094]
			},
			"adresa": {
				"název_kraje": {
					"cs": "Olomoucký"
				},
				"název_okresu": {
					"cs": "Jeseník"
				},
				"název_obce": {
					"cs": "Jeseník"
				}
			}
		}
	},
	{
		"název": {
			"cs": "Kaštany u kostela"
		},
		"poznámka": {
			"cs": "Před kostelem Nanebevzetí Panny Marie asi 50 m od náměstí Svobody ve Zlatých Horách"
		},
		"obrázek": ["https://d34-a.sdn.szn.cz/d_34/c_img_G_U/eo8BXFN.jpeg"],
		"typ_dřeviny": "https://data.mvcr.gov.cz/zdroj/číselníky/typy-dřevin/položky/listnatý-strom",
		"kategorie_ochrany": "https://data.mvcr.gov.cz/zdroj/číselníky/kategorie-územní-ochrany/položky/přírodní-památka",
		"umístění": {
			"geometrie": {
				"type": "LineString",
				"coordinates": [
					[50.26519422535036, 17.398559716715265],
					[50.265107459617475, 17.398591795934845],
					[50.26498719685399, 17.39860601169148]
				]
			},
			"adresa": {
				"název_kraje": {
					"cs": "Olomoucký"
				},
				"název_okresu": {
					"cs": "Jeseník"
				},
				"název_obce": {
					"cs": "Jeseník"
				}
			}
		}
	}
]
