=== datagov-cz/otevrene-formalni-normy/bezbariérovost/draft/schémata/bezbariérovost.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "https://ofn.gov.cz/bezbariérovost/draft/schémata/bezbariérovost.json",
	"type": "object",
	"title": "Bezbariérovost",
	"required": ["typ"],
	"properties": {
		"typ": {
			"const": "Bezbariérovost"
		},
		"popis": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
		},
		"příloha": {
			"$ref": "https://ofn.gov.cz/přílohy/draft/schémata/přílohy.json"
		},
		"okamžik_mapování": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
		},
		"mapující_subjekt": {
			"type": "array",
			"items": {
				"$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
			}
		},
		"mapování_dle_metodiky": {
			"$id": "#/properties/mapovani_dle_metodiky",
			"type": "boolean",
			"tittle": "Mapování dle metodiky kategorizace objektů",
			"examples": [true]
		},
		"přístupnost_děti_s_doprovodem": {
			"type": "array",
			"items": {
				"id": "#/properties/přístupnost_děti_s_doprovodem/items/přístupnost_děti_s_doprovodem",
				"type": "string",
				"format": "iri",
				"pattern": "^https\\:\/\/data\\.mvcr\\.gov\\.cz\/zdroj\/číselníky\/stupně-přístupnosti\/položky\/.*$",
				"title": "Přístupnost pro děti s doprovodem",
				"examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
			}
		},
		"přístupnost_senioři": {
			"type": "array",
			"items": {
				"id": "#/properties/přístupnost_senioři/items/přístupnost_senioři",
				"type": "string",
				"format": "iri",
				"pattern": "^https\\:\/\/data\\.mvcr\\.gov\\.cz\/zdroj\/číselníky\/stupně-přístupnosti\/položky\/.*$",
				"title": "Přístupnost pro seniory",
				"examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
			}
		},
		"tělesně_postižení_toaleta_přístupnost": {
			"type": "array",
			"items": {
				"id": "#/properties/tělesně_postižení_toaleta_přístupnost/items/tělesně_postižení_toaleta_přístupnost",
				"type": "string",
				"format": "iri",
				"pattern": "^https\\:\/\/data\\.mvcr\\.gov\\.cz\/zdroj\/číselníky\/stupně-přístupnosti\/položky\/.*$",
				"title": "Přístupnost toalety pro tělesně postižené",
				"examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
			}
		},
		"tělesně_postižení_objekt_přístupnost": {
			"type": "array",
			"items": {
				"id": "#/properties/tělesně_postižení_objekt_přístupnost/items/tělesně_postižení_objekt_přístupnost",
				"type": "string",
				"format": "iri",
				"pattern": "^https\\:\/\/data\\.mvcr\\.gov\\.cz\/zdroj\/číselníky\/stupně-přístupnosti\/položky\/.*$",
				"title": "Přístupnost objektu pro tělesně postižené",
				"examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
			}
		},
		"objekt_vyhrazené_parkování": {
			"$id": "#/properties/objekt_vyhrazené_parkování",
			"type": "boolean",
			"title": "Vyhrazené parkovací stání",
			"description": "Říká, zda je u objektu alespoň jedno vyhrazené parkovací stání.",
			"default": false,
			"examples": [
				true
			]
		},
		"objekt_obtížný_povrch": {
			"$id": "#/properties/objekt_obtížný_povrch",
			"type": "boolean",
			"title": "Obtížný povrch před objektem",
			"description": "Říká, zda je přístup k objektu obtížný, jedná se zejména o hrubou historickou dlažbu, popraskaný asfalt.",
			"default": false,
			"examples": [
				true
			]
		},
		"objekt_obtížný_sklon": {
			"$id": "#/properties/objekt_obtížný_sklon",
			"type": "boolean",
			"title": "Obtížný povrch před objektem",
			"description": "Říká, zda je přístup k objektu obtížný z důvodu výrazného podélného nebo příčného sklonu.",
			"default": false,
			"examples": [
				true
			]
		},
		"vstup_hlavní_vchod": {
			"$id": "#/properties/vstup_hlavní_vchod",
			"type": "boolean",
			"title": "Objekt přístupný hlavním vchodem",
			"description": "Říká, zda je do objektu bezbariérový přístup hlavním vchodem.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_schody": {
			"$id": "#/properties/vstup_hlavní_schody",
			"type": "integer",
			"title": "Počet schodů u hlavního vstupu",
			"description": "Říká, kolik je schodů před hlavním vstupem do objektu bez řešení jejich bezbariérového překonání.",
			"default": 0,
			"examples": [
				18
			]
		},
		"vstup_hlavní_nájezd": {
			"$id": "#/properties/vstup_hlavní_nájezd",
			"type": "boolean",
			"title": "Nájezd u hlavního vstupu",
			"description": "Říká, zda je u hlavního vstupu nájezd (rampa nebo ližiny) pro bezbariérový přístup do objektu. Šířka pevných ramp je minimálně 110 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_plošina": {
			"$id": "#/properties/vstup_hlavní_plošina",
			"type": "boolean",
			"title": "Plošina u hlavního vstupu",
			"description": "Říká, zda je u hlavního vstupu schodišťová plošina pro bezbariérový přístup do objektu. Rozměry plošiny jsou minimálně: šířka vstupu 70 cm, přepravní plocha – šířka 70 cm x hloubka 90 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_výtah": {
			"$id": "#/properties/vstup_hlavní_výtah",
			"type": "boolean",
			"title": "Výtah u hlavního vstupu",
			"description": "Říká, zda je u hlavního vstupu výtah (zdviž) pro bezbariérový přístup do objektu. Výtah má minimální rozměry: šířka dveří 70cm, vnitřní rozměr kabiny – šířka 100 cm x hloubka 110 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_výtah_sedátko": {
			"$id": "#/properties/vstup_hlavní_výtah_sedátko",
			"type": "boolean",
			"title": "Sedátko ve výtahu u hlavního vstupu",
			"description": "Říká, zda je výtah (zdviž) u hlavního vstupu vybaven sklopným sedátkem.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_výtah_madlo": {
			"$id": "#/properties/vstup_hlavní_výtah_madlo",
			"type": "boolean",
			"title": "Madlo ve výtahu u hlavního vstupu",
			"description": "Říká, zda je výtah (zdviž) u hlavního vstupu vybeven madlem.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_hlavní_šířka_dveří": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
		},
		"vstup_vedlejší_vchod": {
			"$id": "#/properties/vstup_vedlejší_vchod",
			"type": "boolean",
			"title": "Objekt přístupný vedlejším vchodem",
			"description": "Říká, zda je do objektu bezbariérový přístup vedlejším vchodem.",
			"default": false,
			"examples": [
				true
			]
		},
		"vstup_vedlejší_schody": {
			"$id": "#/properties/vstup_vedlejší_schody",
			"type": "integer",
			"title": "Počet schodů u vedlejšího vstupu",
			"description": "Říká, kolik je schodů před vedlejším vstupem do objektu bez řešení jejich bezbariérového překonání.",
			"default": 0,
			"examples": [
				0
			]
		},
		"vstup_vedlejší_nájezd": {
			"$id": "#/properties/vstup_vedlejší_nájezd",
			"type": "boolean",
			"title": "Nájezd u vedlejšího vstupu",
			"description": "Říká, zda je u vedlejšího vstupu nájezd (rampa nebo ližiny) pro bezbariérový přístup do objektu. Šířka pevných ramp je minimálně 110 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_vedlejší_plošina": {
			"$id": "#/properties/vstup_vedlejší_plošina",
			"type": "boolean",
			"title": "Plošina u vedlejšího vstupu",
			"description": "Říká, zda je u vedlejšího vstupu schodišťová plošina pro bezbariérový přístup do objektu. Rozměry plošiny jsou minimálně: šířka vstupu 70 cm, přepravní plocha – šířka 70 cm x hloubka 90 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_vedlejší_výtah": {
			"$id": "#/properties/vstup_vedlejší_výtah",
			"type": "boolean",
			"title": "Výtah u vedlejšího vstupu",
			"description": "Říká, zda je u vedlejšího vstupu výtah (zdviž) pro bezbariérový přístup do objektu. Výtah má minimální rozměry: šířka dveří 70cm, vnitřní rozměr kabiny – šířka 100 cm x hloubka 110 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_vedlejší_výtah_sedátko": {
			"$id": "#/properties/vstup_vedlejší_výtah_sedátko",
			"type": "boolean",
			"title": "Sedátko ve výtahu u vedlejšího vstupu",
			"description": "Říká, zda je výtah (zdviž) u vedlejšího vstupu vybaven sklopným sedátkem.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_vedlejší_výtah_madlo": {
			"$id": "#/properties/vstup_vedlejší_výtah_madlo",
			"type": "boolean",
			"title": "Madlo ve výtahu u vedlejšího vstupu",
			"description": "Říká, zda je výtah (zdviž) u vedlejšího vstupu vybaven madlem.",
			"default": false,
			"examples": [
				false
			]
		},
		"vstup_vedlejší_šířka_dveří": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
		},
		"interiér_schody": {
			"$id": "#/properties/interiér_schody",
			"type": "integer",
			"title": "Počet schodů v interiéru",
			"description": "Říká, kolik je v interiéru nejvíce schodů, které nespojují patra.",
			"default": 0,
			"examples": [
				5
			]
		},
		"interiér_minimální_průchod": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
		},
		"interiér_výška_prahu": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
		},
		"interiér_přístupnost": {
			"$id": "#/properties/interiér_přístupnost",
			"type": "boolean",
			"title": "Přístupný interiér",
			"description": "Říká, zda je přístupný celý interiér nebo jeho větší část alespoň jedním bezbariérovým vstupem. Návštěva je možná bez předchozí domluvy.",
			"default": false,
			"examples": [
				false
			]
		},
		"interiér_nájezd": {
			"$id": "#/properties/interiér_nájezd",
			"type": "boolean",
			"title": "Nájezd v interiéru",
			"description": "Říká, zda je v interiéru nájezd (rampa nebo ližiny) pro překonání výškových rozdílů. Šířka pevných ramp je minimálně 110 cm.",
			"default": false,
			"examples": [
				true
			]
		},
		"interiér_plošina": {
			"$id": "#/properties/interiér_plošina",
			"type": "boolean",
			"title": "Plošina v interiéru",
			"description": "Říká, zda je v interiéru schodišťová plošina. Rozměry plošiny jsou minimálně: šířka vstupu 70 cm, přepravní plocha – šířka 70 cm x hloubka 90 cm.",
			"default": false,
			"examples": [
				false
			]
		},
		"interiér_výtah": {
			"$id": "#/properties/interiér_výtah",
			"type": "boolean",
			"title": "Výtah v interiéru",
			"description": "Říká, zda je v interiéru výtah (zdviž). Výtah má minimální rozměry: šířka dveří 70cm, vnitřní rozměr kabiny – šířka 100 cm x hloubka 110 cm.",
			"default": false,
			"examples": [
				true
			]
		},
		"interiér_výtah_sedátko": {
			"$id": "#/properties/interiér_výtah_sedátko",
			"type": "boolean",
			"title": "Sedátko ve výtahu v interiéru",
			"description": "Říká, zda je výtah (zdviž) v interiéru vybaven sklopným sedátkem.",
			"default": false,
			"examples": [
				true
			]
		},
		"interiér_výtah_madlo": {
			"$id": "#/properties/interiér_výtah_madlo",
			"type": "boolean",
			"title": "Madlo ve výtahu v interiéru",
			"description": "Říká, zda je výtah (zdviž) v interiéru vybaven madlem.",
			"default": false,
			"examples": [
				true
			]
		},
		"interiér_točité_schodiště": {
			"$id": "#/properties/interiér_točité_schodiště",
			"type": "boolean",
			"title": "Točité schodiště v interiéru",
			"description": "Říká, zda je v interiéru točité schodiště.",
			"default": false,
			"examples": [
				false
			]
		},
		"toaleta_šířka_dveří": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
		},
		"toaleta_klíč": {
			"$id": "#/properties/toaleta_klíč",
			"type": "boolean",
			"title": "Dveře na toaletu uzamčené",
			"description": "Říká, zda jsou vstupní dveře na toaletu uzamčeny.",
			"default": false,
			"examples": [
				false
			]
		},
		"toaleta_euroklíč": {
			"$id": "#/properties/toaleta_euroklíč",
			"type": "boolean",
			"title": "Dveře na toaletu uzamčené Euroklíčem",
			"description": "Říká, zda jsou vstupní dveře na toaletu osazeny Eurozámkem. Více informací na stránkách projektu Euroklíč.",
			"default": false,
			"examples": [
				false
			]
		},
		"toaleta_dostatečný_rozměr": {
			"$id": "#/properties/toaleta_dostatečný_rozměr",
			"type": "boolean",
			"title": "Dostatečný rozměr kabiny toalety",
			"description": "Říká, zda je rozměr kabiny toalety minimální šířky 140 cm a hloubky 140 cm. Manipulační prostor je pak umístěný proti dveřím.",
			"default": false,
			"examples": [
				true
			]
		},
		"toaleta_signalizační_tlačítko": {
			"$id": "#/properties/toaleta_signalizační_tlačítko",
			"type": "boolean",
			"title": "Signalizační tlačítko na toaletě",
			"description": "Říká, zda je toaleta vybavena signalizačním tlačítkem pro přivolání pomoci.",
			"default": false,
			"examples": [
				false
			]
		},
		"toaleta_wc_boční_přístup": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
		},
		"toaleta_wc_výška_sedátka": {
			"$id": "#/properties/toaleta_wc_výška_sedátka",
			"type": "boolean",
			"title": "Dostatečná výška sedátka WC",
			"description": "Říká, zda je výška sedátka WC mísy alespoň 45cm.",
			"default": false,
			"examples": [
				true
			]
		},
		"toaleta_wc_madlo": {
			"$id": "#/properties/toaleta_wc_madlo",
			"type": "boolean",
			"title": "Madlo u WC",
			"description": "Říká, zda je u WC alespoň jedno madlo.",
			"default": false,
			"examples": [
				true
			]
		},
		"toaleta_umyvadlo_dostatečný_prostor": {
			"$id": "#/properties/toaleta_umyvadlo_dostatečný_prostor",
			"type": "boolean",
			"title": "Dostatečný prostor pod umyvadlem",
			"description": "Říká, zda je podjezd umyvadla v hloubce 20 cm od jeho hrany dostatečný pro podjetí vozíku pro invalidy.",
			"default": false,
			"examples": [
				true
			]
		},
		"toaleta_přebalovací_pult": {
			"$id": "#/properties/toaleta_přebalovací_pult",
			"type": "boolean",
			"title": "Přebalovací pult na toaletě",
			"description": "Říká, zda je toaleta vybavena přebalovacím pultem.",
			"default": false,
			"examples": [
				false
			]
		},
		"Braillovo_písmo": {
			"$id": "#/properties/braillovo_písmo",
			"type": "boolean",
			"title": "Braillovo písmo",
			"examples": [true]
		},
		"hlasový_asistent": {
			"$id": "#/properties/hlasový_asistent",
			"type": "boolean",
			"tittle": "Hlasový asistent",
			"examples": [true]
		},
		"vodící_linie": {
			"$id": "#/propertie/vodící_linie",
			"type": "boolean",
			"tittle": "Vodící linie",
			"examples": [true]
		},
		"vodící_pes": {
			"$id": "#/properties/vodící_pes",
			"type": "boolean",
			"tittle": "Vodící pes",
			"examples": [true]
		}
	}
}

=== datagov-cz/otevrene-formalni-normy/bezbariérovost/draft/příklady/3.json
{
	"typ": "Bezbariérovost",
	"popis": {
		"cs": "Parkování: Parkování je možné přímo na parkovišti u hospitalu Kuks odbočením ze silnice č. 37 a projetím obce Slotov. Na parkovišti jsou 2 vyhrazené parkovací stání. Povrch parkoviště tvoří velké kostky.\n Vstup: Přístup ke vstupům do objektu vede po chodníku, který je zpevněn kamínky. Vstup do pokladny vede přes vchod (šířka 181 cm) do závětří. Návštěvou objektu Kuks je možné absolvovat 2 prohlídkové okruhy (1. Hospital, 2. Šporkovská hrobka). Hlavní vstup na 1. okruh se nalézá několik desítek metrů za vstupem do závětří. K němu je potřeba zdolat schodiště čítající 18 schodů (výška 18 cm, hloubka 36 cm). U samotného vstupu jsou dvoukřídlé mechanické dveře s otevíráním dovnitř (šířky hlavního křídla 64 cm a vedlejšího křídla 70 cm). Jako vedlejší vstup lze využít zmíněný vchod do závětří (šířka 181 cm). 2. okruh se nachází mimo hlavní objekt hospitalu. Pro vstup na 2. okruh je třeba překonat schodiště o 30 schodech. Samotný vstup do hrobky je tvořen dvoukřídlou mříží s otevíráním dovnitř.\n Interiér: Samotný hospital má 2 prohlídkové okruhy. 1. okruh vede z větší části po 2. NP, do něhož je možné se dostat jak po schodišti, tak výtahem při využití vedlejšího vstupu. V samotném podlaží se nevyskytují jednotlivé schody, vyskytují se jen prahy do 5 cm. Pouze při vstupu do lékárny je nutné překonat 9 cm práh. Prohlídkový okruh vede krom 2. NP i přes nádvoří do lapidária. Do nádvoří se lze dostat bezbariérově za pomoci výtahu. Bez využití výtahu by bylo nutné překonat schodiště o 5 schodech (max. šířka 270 cm). Nádvoří je již pak bezbariérové. Do lapidária je možné se dostat za pomoci nainstalované mobilní rampy. 2. okruh je přístupný pouze za předpokladu překonání schodiště před vstupem. V samotném objektu hrobky se potom nachází 3 schody (šířka 175 cm, výška 18 cm, hloubka 50 cm).\nWC: V objektu Kuksu se nalézají 2 bezbariérové WC. První WC se nachází v objektu Kuksu v 1. NP a je veřejnosti volně přístupné. Dveře do kabiny WC nesou označení pro hendikepované. Dveře šířky 81 cm vedou do kabiny o šířce 357 cm a hloubce 225 cm. Vypínač je ve výšce 91 cm. Záchodová mísa je odsazena od pravé stěny 141 cm. Výška sedátka mísy je 49 cm. Levé madlo je pevné o délce 83 cm a výšce 78 cm. Pravé madlo je sklopné o délce 83 cm a výšce 78 cm. Umyvadlo je umístěno ve výšce 83 cm. Druhé WC se nachází v objektu Kuksu ve 2. NP a je veřejnosti volně přístupné. Dveře do kabiny WC nesou označení pro hendikepované. Dveře šířky 93 cm vedou do kabiny o šířce 180 cm a hloubce 241 cm. Vypínač je ve výšce 93 cm. Záchodová mísa je odsazena od levé stěny 95 cm. Výška sedátka mísy je 52 cm. Levé madlo je mobilní o délce 80 cm a výšce 78 cm. Pravé madlo je pevné o délce 80 cm a výšce 78 cm. Umyvadlo je umístěno ve výšce 82 cm.\nVýtah: Výtah v objektu je umístěn po vstupu vedlejším vstupem na druhé straně objektu. Jedná se o výtah, který je uzamčen a přístup do něho zajistí průvodce. Dojezd výtahu je na hlavních podestách. Šířka šachetních dveří je 88 cm a klecových dveří 101 cm. Šířka klece je 101 cm a hloubka 183 cm.\n Rampa: Rampa se nachází před vstupem do lapidária. Jedná se o rampu mobilní a přístup zajistí průvodce. Sklon rampy je 18,5 %, šířka 94 cm a délka 185 cm, povrch je nekluzký. Madlo u rampy z důvodu mobility chybí.",
		"en": "Parking: Parking is possible directly in the parking lot at the Kuks hospital by turning off the road No. 37 and passing the village Slotov. There are 2 reserved parking spaces in the parking lot. The surface of the car park is made up of large cubes. \n Entrance: Access to the entrances to the building leads along a sidewalk that is paved with stones. The entrance to the cash register leads through the entrance (width 181 cm) to the lee. By visiting the Kuks building, it is possible to complete 2 sightseeing tours (1st Hospital, 2nd Šporkovská Tomb). The main entrance to the 1st circuit is located several tens of meters behind the entrance to the lee. To do this, you need to climb a staircase numbering 18 steps (height 18 cm, depth 36 cm). At the entrance itself, there is a double-leaf mechanical door with inward opening (width of the main leaf 64 cm and side leaf 70 cm). The mentioned entrance to the lee (width 181 cm) can be used as a side entrance. The 2nd circuit is located outside the main building of the hospital. To enter the 2nd circuit, it is necessary to climb a staircase of 30 steps. The entrance to the tomb itself is formed by a double-leaf lattice with an opening inwards. \n Interior: The hospital itself has 2 sightseeing tours. The 1st circuit leads for the most part along the 2nd floor, which can be reached both by stairs and by elevator using the side entrance. There are no individual stairs in the floor itself, there are only thresholds up to 5 cm. It is only necessary to cross the 9 cm threshold when entering the pharmacy. Apart from the 2nd floor, the sightseeing circuit leads across the courtyard to the lapidary. The courtyard can be reached by a lift. Without the use of an elevator, it would be necessary to overcome a staircase of 5 steps (max. Width 270 cm). The courtyard is then barrier-free. It is possible to get to the lapidary with the help of an installed mobile ramp. The 2nd circuit is accessible only if the stairs are crossed before entering. There are then 3 steps in the tomb building itself (width 175 cm, height 18 cm, depth 50 cm). \n WC: There are 2 barrier-free toilets in the Kuksu building. The first toilet is located in the Kuksu building on the 1st floor and is open to the public. The door to the toilet cubicle is marked for the disabled. The 81 cm wide door leads to a cabin 357 cm wide and 225 cm deep. The switch is 91 cm high. The toilet bowl is offset from the right wall 141 cm. The height of the bowl seat is 49 cm. The left handle is fixed with a length of 83 cm and a height of 78 cm. The right handle is foldable with a length of 83 cm and a height of 78 cm. The washbasin is located at a height of 83 cm. The second toilet is located in the Kuksu building on the 2nd floor and is open to the public. The door to the toilet cubicle is marked for the disabled. The 93 cm wide door leads into a cabin 180 cm wide and 241 cm deep. The switch is 93 cm high. The toilet bowl is offset from the left wall 95 cm. The height of the bowl seat is 52 cm. The left handle is mobile with a length of 80 cm and a height of 78 cm. The right handle is fixed with a length of 80 cm and a height of 78 cm. The washbasin is located at a height of 82 cm. \n Elevator: The elevator in the building is located after entering by a side entrance on the other side of the building. It is a lift that is locked and can be accessed by a guide. The lift is reached on the main landings. The width of the shaft door is 88 cm and the cage door 101 cm. The width of the cage is 101 cm and the depth 183 cm. \n Ramp: The ramp is located in front of the entrance to the lapidary. It is a mobile ramp and access is provided by a guide. The slope of the ramp is 18.5%, width 94 cm and length 185 cm, the surface is non-slip. The handrail at the ramp is missing due to mobility."
	},
	"okamžik_mapování": {
		"typ": "Časový okamžik",
		"datum_a_čas": "2019-09-27T09:30:00+02:00"
	},
	"příloha": [{
		"typ": "Digitální objekt",
		"url": "http://www.presbariery.cz/images/objekty/item_12555_field_54/l_img_20160914_131606.jpg",
		"autor": [{
			"typ": "Člověk",
			"jméno": {
                "cs": "Jan"
            },
            "příjmení": {
                "cs": "Novák"
            }
		}],
		"typ_media": "http://www.iana.org/assignments/media-types/image/jpeg",
		"podmínky_užití": {
			"autorské_dílo": "https://data.gov.cz/podmínky-užití/neobsahuje-autorská-díla/",
			"databáze_autorské_dílo": "https://data.gov.cz/podmínky-užití/není-autorskoprávně-chráněnou-databází/",
			"databáze_zvláštní_práva": "https://data.gov.cz/podmínky-užití/není-chráněna-zvláštním-právem-pořizovatele-databáze/",
			"osobní_údaje": "https://data.gov.cz/podmínky-užití/neobsahuje-osobní-údaje",
			"autoři_díla": "František Svoboda",
			"autoři_originální_databáze": "František Novák"
		}
	}],
	"mapující_subjekt": [{
		"typ": "Osoba",
		"ičo": "00676098",
		"název": {
			"cs": "Pražská organizace vozíčkářů, z.s."
		}
	}],
	"mapování_dle_metodiky": true,
	"tělesně_postižení_toaleta_přístupnost": [
		"https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"
	],
	"tělesně_postižení_objekt_přístupnost": [
		"https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"
	],
	"objekt_obtížný_povrch": true,
	"objekt_obtížný_sklon": true,
	"vstup_hlavní_vchod": false,
	"vstup_vedlejší_vchod": true,
	"interiér_plošina": false,
	"interiér_výtah": true,
	"interiér_točité_schodiště": false
}
